### ISSUE TITLE
how to configure dwm.c ?

### ISSUE THREAD

**Issue by Elmiar0642** [metis-os/metis-dwm#1]
How to configure dwm.c.

I want to add key binding for screenshot utility.

**Comment by pwnwriter** [comment]
Hi, if you want to add screenshot utility add in the configuration file ft:`config.def.h` no need to change `dwm.c` file. Can you please specify which tool do you want to add? so that i can configure accordingly...
options are: 1) imagemagick
             2) scrot
             3) flameshot 
or any other you are known off?
thanks:)
